import{a as m,S as b,i as n}from"./assets/vendor-DEenWwFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();async function u(s,r=1,o=15){const l="https://pixabay.com/api/",e="47394920-a4032b33a38ab12c89a369f6a",t=new URLSearchParams({key:e,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:o});try{return(await m(l,{params:t})).data}catch(a){throw iziToast.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),a}}function g(s){return s.map(({webformatURL:r,largeImageURL:o,tags:l,likes:e,views:t,comments:a,downloads:f})=>`
        <div class="gallery-card">
            <a class="gallery-item" href="${o}">
            <div class="all-gallery">
            <img class="gallery-img" src="${r}" alt="${l}">
            <div class="discription">
            <p class="discr-text">Likes <span>${e}</span></p>
            <p class="discr-text">Views <span>${t}</span></p>
            <p class="discr-text">Comments <span>${a}</span></p>
            <p class="discr-text">Downloads <span>${f}</span></p>
            </div>
            </div>
            </a>
        </div>
    
    `).join("")}const S=document.querySelector(".search-form"),y=document.querySelector(".gallery"),i=document.querySelector(".load-btn-js"),p=document.querySelector(".loader");p.style.display="none";let h=new b(".gallery-item",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250}),c=1,d="";i.style.display="none";S.addEventListener("submit",R);i.addEventListener("click",w);async function R(s){if(s.preventDefault(),y.innerHTML="",d=s.target.elements.query.value.trim(),c=1,d===""){n.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.style.display="none";return}p.style.display="block";try{const r=await u(d,c);if(r.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.style.display="none";return}else if(c*15>=r.totalHits){i.style.display="none",n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const o=g(r.hits);y.innerHTML=o,h.refresh(),i.style.display="block"}catch{n.error({title:"Error",message:"Something went wrong. Please try again later",position:"topRight"})}finally{p.style.display="none",s.target.reset()}}async function w(){c+=1,p.style.display="block";try{const s=await u(d,c);if(s.hits.length===0){n.info({title:"End of Results",message:"No more images to load.",position:"topRight"}),i.style.display="none";return}else if(c*15>=s.totalHits){i.style.display="none",n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const r=g(s.hits);y.insertAdjacentHTML("beforeend",r);let o=()=>document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o().height*2,left:0,behavior:"smooth"}),h.refresh()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p.style.display="none"}}
//# sourceMappingURL=index.js.map
