import{a as m,S,i as n}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function u(s,t=1,a=15){const l="https://pixabay.com/api/",e="47394920-a4032b33a38ab12c89a369f6a",r=new URLSearchParams({key:e,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:a});try{return(await m(l,{params:r})).data}catch(i){throw iziToast.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),i}}function g(s){return s.map(({webformatURL:t,largeImageURL:a,tags:l,likes:e,views:r,comments:i,downloads:f})=>`
        <div class="gallery-card">
            <a class="gallery-item" href="${a}">
            <div class="all-gallery">
            <img class="gallery-img" src="${t}" alt="${l}">
            <div class="discription">
            <p class="discr-text">Likes <span>${e}</span></p>
            <p class="discr-text">Views <span>${r}</span></p>
            <p class="discr-text">Comments <span>${i}</span></p>
            <p class="discr-text">Downloads <span>${f}</span></p>
            </div>
            </div>
            </a>
        </div>
    
    `).join("")}const b=document.querySelector(".search-form"),d=document.querySelector(".gallery"),o=document.querySelector(".load-btn-js"),c=document.querySelector(".loader");c.style.display="none";let h=new S(".gallery-item",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250}),y=1,p="";o.style.display="none";b.addEventListener("submit",R);o.addEventListener("click",w);async function R(s){if(s.preventDefault(),d.innerHTML="",p=s.target.elements.query.value.trim(),y=1,p===""){n.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),o.style.display="none";return}c.style.display="block",o.style.display="none";try{const t=await u(p,y);if(t.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),o.style.display="none";return}const a=g(t.hits);d.innerHTML=a,h.refresh(),t.totalHits<=t.hits.length?(o.style.display="none",n.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):o.style.display="block"}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{c.style.display="none",s.target.reset()}}async function w(){y+=1,c.style.display="block",o.style.display="none";try{const s=await u(p,y);if(s.hits.length===0){n.info({title:"End of Results",message:"No more images to load.",position:"topRight"}),o.style.display="none";return}const t=g(s.hits);d.insertAdjacentHTML("beforeend",t);let a=()=>document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a().height*2,left:0,behavior:"smooth"}),h.refresh(),d.children.length>=s.totalHits?(o.style.display="none",n.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):o.style.display="block"}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{c.style.display="none"}}
//# sourceMappingURL=index.js.map
